---
title: Varun Chopra
timezone: UTC
collections:
  blog:
    title: Blog
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
defaults:
- scope:
    path: work
    type: posts
  values:
    layout: default
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: posts
    type: posts
  values:
    layout: work
- scope:
    path: ''
  values:
    layout: default
permalink: pretty
exclude:
- ".git"
- ".gitignore"
- ".DS_Store"
- CNAME
- ".sass-cache"
- package.json
- Gruntfile.js
- node_modules
- README.md
- Gemfile
- Gemfile.lock
- LICENSE
image: "/uploads/mug1.jpg"
intro: Varun Chopra is a filmmaker, director and student working &amp; living out
  of sunny Los Angeles, California.
