---
title: Varun Chopra
url: http://beta.varunchoprafilms.com
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: default
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
baseurl: http://beta.varunchoprafilms.com
permalink: pretty
exclude:
- ".git"
- ".gitignore"
- ".DS_Store"
- CNAME
- ".sass-cache"
- package.json
- Gruntfile.js
- node_modules
- README.md
- Gemfile
- Gemfile.lock
- LICENSE
