---
---

---
title: Varun Chopra
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  blog:
    title: Blog
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
defaults:
- scope:
    path: ""
    type: "work"
  values:
    layout: "work"
- scope:
    path: ""
    type: posts
  values:
    layout: "default"
    permalink: "/posts/:title/"
- scope:
    path: 'posts'
    type: posts
  values:
    layout: work
- scope:
    path: ""
    type: "pages"
  values:
    layout: default
permalink: pretty
exclude: [
  .git,
  .gitignore,
  .DS_Store,
  CNAME,
  # svg-icons,
  # svg-decorations,
  # scss,
  .sass-cache,
  package.json,
  Gruntfile.js,
  node_modules,
  README.md,
  Gemfile,
  Gemfile.lock,
  LICENSE,
]
